-- ============================================================
-- Eightysixdegrees Punchcard — reset all customer data
-- ============================================================
-- Run this in the Supabase SQL Editor for
-- https://edunsrtcdhnpbsipalhc.supabase.co when you're ready to start
-- fresh (e.g. clearing out test signups before a real launch).
--
-- THIS IS IRREVERSIBLE. Read before running.
--
-- WHAT THIS DELETES:
--   - Every customer account: stamps, rewards, activity history,
--     usernames/passwords, and any Google-linked accounts.
--   - Everything that references a customer row via ON DELETE CASCADE:
--     login sessions (customer_sessions), push notification
--     subscriptions (push_subscriptions), friend requests/friendships
--     (customer_friend_requests), and in-app notifications
--     (customer_notifications) — nothing extra to run, Postgres clears
--     these automatically as part of the same delete.
--   - Referral links (customers.referred_by, a customer referencing
--     another customer's id): safe here specifically because this is
--     ONE statement deleting every row at once — Postgres checks that
--     constraint at the end of the statement, by which point nothing is
--     left to violate it. Do not turn this into a filtered/looped
--     delete without also handling that column, or it can fail.
--
-- WHAT THIS DOES NOT TOUCH:
--   - Staff accounts (Stacy/Kiko/Iva) and their sessions — you'll
--     still be able to log into the Staff Portal afterward.
--   - The stamp campaign setting (e.g. Double Stamps toggle/label).
--   - The menu (that's stored per-device in the browser, not here).
--
-- After running this, every device that has the app open will still
-- show its locally cached card until it next syncs or reloads — that's
-- expected; the cloud copy is gone, so nothing will save back to it.
-- ============================================================

delete from public.customers;
